.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LV2_INSPECT 1 "4 May 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.B lv2info \- print information about an LV2 plugin in human-readable form.
.SH SYNOPSIS
.B lv2info PLUGIN_URI

.SH SEE ALSO
.BR lilv(3),
.BR lv2_list(1),
.BR lv2_jack_host(1),

.SH AUTHOR
lv2info was written by David Robillard <d@drobilla.net>
.PP
This manual page was written by Jaromír Mikes <mira.mikes@seznam.cz>
and David Robillard <d@drobilla.net>
